name: Run Omnivore Newsletter

on:
  schedule:
    - cron: "0 8 * * *"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.2
        with:
          deno-version: v1.38.1

      - name: Run linter
        run: deno lint

      - name: Run Script
        env:
          OMNIVORE_KEY: ${{ secrets.OMNIVORE_KEY }}
          SMTP_HOSTNAME: ${{ secrets.SMTP_HOSTNAME }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          SMTP_TO: ${{ secrets.SMTP_TO }}
        run: deno run --allow-all main.ts
